# Generated by Django 5.2.17 on 2026-09-23 17:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nome",
            field=models.CharField(
                default="",
                help_text="Nome de usuário",
                max_length=100,
                validators=[accounts.models.validar_nickname_apropriado],
            ),
            preserve_default=False,
        ),
    ]
