# Generated by Django 5.2.17 on 2026-09-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ano_nascimento",
            field=models.SmallIntegerField(
                help_text="Finalidade (LGPD): Mapeamento demográfico da faixa etária do público-alvo, sem retenção de dados pessoais sensíveis."
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Finalidade: Controle de status da conta para retenção e controle.",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Finalidade: Registro de auditoria técnica informando quando os dados foram coletados.",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="Finalidade: Utilizado como credencial de login e para envio de comunicações essenciais do sistema.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="google_oid",
            field=models.CharField(
                blank=True,
                help_text="Finalidade: Identificador único para viabilizar o login rápido e seguro via autenticação federada (Google OAuth 2.0).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_completo",
            field=models.CharField(
                help_text="Finalidade: Identificação do usuário e personalização da interface.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="perfil",
            field=models.CharField(
                help_text="Finalidade: Definição de permissões e controle de acesso (ex: Aluno ou Administrador).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="senha_hash",
            field=models.CharField(
                help_text="Finalidade: Autenticação e proteção das credenciais de acesso.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Finalidade: Registro de auditoria técnica para rastrear a última modificação dos dados.",
            ),
        ),
    ]
