# Generated by Django 5.2.17 on 2026-09-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_usuario_ano_nascimento_alter_usuario_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ano_nascimento",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="google_oid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_completo",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="perfil",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="senha_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
