# Generated by Django 5.2.17 on 2026-09-05 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glossario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("termo", models.CharField(max_length=100, unique=True)),
                ("definicao", models.TextField()),
                ("figura_svg", models.TextField(blank=True, null=True)),
                ("categoria", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "TB_GLOSSARIO",
            },
        ),
    ]
