# Generated by Django 5.2.17 on 2026-09-05 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordem", models.IntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "TB_MODULO",
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordem", models.IntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("conteudo_teorico", models.TextField()),
                ("partitura_dados", models.JSONField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="learning.modulo",
                    ),
                ),
            ],
            options={
                "db_table": "TB_AULA",
            },
        ),
    ]
