# Generated by Django 5.2.17 on 2026-09-05 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressoAula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("concluida", models.BooleanField(default=False)),
                (
                    "taxa_acerto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acompanhamentos",
                        to="learning.aula",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="accounts.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "TB_PROGRESSO_AULA",
            },
        ),
    ]
