/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PraticaRouteImport } from './routes/pratica'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminSistemaRouteImport } from './routes/admin.sistema'
import { Route as LicaoLessonIdRouteImport } from './routes/licao.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticaRoute = PraticaRouteImport.update({
  id: '/pratica',
  path: '/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/admin/conteudo',
  path: '/admin/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/admin/sistema',
  path: '/admin/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoLessonIdRoute = LicaoLessonIdRouteImport.update({
  id: '/licao/$lessonId',
  path: '/licao/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/painel': typeof PainelRoute
  '/pratica': typeof PraticaRoute
  '/registro': typeof RegistroRoute
  '/triagem': typeof TriagemRoute
  '/trilha': typeof TrilhaRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/painel': typeof PainelRoute
  '/pratica': typeof PraticaRoute
  '/registro': typeof RegistroRoute
  '/triagem': typeof TriagemRoute
  '/trilha': typeof TrilhaRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossario': typeof GlossarioRoute
  '/painel': typeof PainelRoute
  '/pratica': typeof PraticaRoute
  '/registro': typeof RegistroRoute
  '/triagem': typeof TriagemRoute
  '/trilha': typeof TrilhaRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossario'
    | '/painel'
    | '/pratica'
    | '/registro'
    | '/triagem'
    | '/trilha'
    | '/admin/conteudo'
    | '/admin/sistema'
    | '/licao/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossario'
    | '/painel'
    | '/pratica'
    | '/registro'
    | '/triagem'
    | '/trilha'
    | '/admin/conteudo'
    | '/admin/sistema'
    | '/licao/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/glossario'
    | '/painel'
    | '/pratica'
    | '/registro'
    | '/triagem'
    | '/trilha'
    | '/admin/conteudo'
    | '/admin/sistema'
    | '/licao/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossarioRoute: typeof GlossarioRoute
  PainelRoute: typeof PainelRoute
  PraticaRoute: typeof PraticaRoute
  RegistroRoute: typeof RegistroRoute
  TriagemRoute: typeof TriagemRoute
  TrilhaRoute: typeof TrilhaRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminSistemaRoute: typeof AdminSistemaRoute
  LicaoLessonIdRoute: typeof LicaoLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratica': {
      id: '/pratica'
      path: '/pratica'
      fullPath: '/pratica'
      preLoaderRoute: typeof PraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/admin/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sistema': {
      id: '/admin/sistema'
      path: '/admin/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao/$lessonId': {
      id: '/licao/$lessonId'
      path: '/licao/$lessonId'
      fullPath: '/licao/$lessonId'
      preLoaderRoute: typeof LicaoLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossarioRoute: GlossarioRoute,
  PainelRoute: PainelRoute,
  PraticaRoute: PraticaRoute,
  RegistroRoute: RegistroRoute,
  TriagemRoute: TriagemRoute,
  TrilhaRoute: TrilhaRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminSistemaRoute: AdminSistemaRoute,
  LicaoLessonIdRoute: LicaoLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
