# Generated by Django 5.2.17 on 2026-09-19 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=100, unique=True)),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("icone_url", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "TB_BADGE",
            },
        ),
        migrations.CreateModel(
            name="GamificacaoPerfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("streak_atual", models.IntegerField(default=0)),
                ("melhor_streak", models.IntegerField(default=0)),
                ("ultimo_acesso_estudo", models.DateField(blank=True, null=True)),
                ("pontuacao_total", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamificacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "TB_GAMIFICACAO_PERFIL",
            },
        ),
        migrations.CreateModel(
            name="UsuarioBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_conquista", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.badge",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_conquistadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "TB_USUARIO_BADGE",
            },
        ),
    ]
