# Generated by Django 5.2.17 on 2026-09-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("acao", models.CharField(max_length=255)),
                ("ip_origem", models.GenericIPAddressField()),
                ("detalhes", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "TB_LOG_AUDITORIA",
            },
        ),
    ]
