# Generated by Django 5.2.17 on 2026-09-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_usuario_ano_nascimento_alter_usuario_ativo_and_more"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="acao",
            field=models.CharField(
                help_text="Finalidade: Descrição da ação crítica realizada no sistema.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Finalidade: Carimbo de data/hora (UTC) do evento (Log).",
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="detalhes",
            field=models.JSONField(
                blank=True,
                help_text="Finalidade: Payload ou metadados da requisição para rastreabilidade de falhas.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="ip_origem",
            field=models.GenericIPAddressField(
                help_text="Finalidade: Requisito de segurança e auditoria técnica (rastreabilidade)."
            ),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Finalidade: Identificação do titular associado à ação (mantido nulo se a conta for excluída para anonimização).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.usuario",
            ),
        ),
    ]
