# Generated by Django 5.2.17 on 2026-09-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usuario_ano_nascimento_alter_usuario_ativo_and_more"),
        ("audit", "0002_alter_logauditoria_acao_alter_logauditoria_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="acao",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="detalhes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="ip_origem",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.usuario",
            ),
        ),
    ]
