# Generated by Django 5.2.17 on 2026-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_logauditoria_acao_alter_logauditoria_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="ip_origem",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
