# Generated by Django 5.2.17 on 2026-09-19 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("enunciado", models.TextField()),
                ("gabarito_dados", models.JSONField()),
                ("tag_topico", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicios",
                        to="learning.aula",
                    ),
                ),
            ],
            options={
                "db_table": "TB_EXERCICIO",
            },
        ),
        migrations.CreateModel(
            name="TentativaExercicio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acertou", models.BooleanField()),
                ("tempo_resposta_ms", models.IntegerField()),
                ("realizada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentativas_recebidas",
                        to="exercises.exercicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentativas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "TB_TENTATIVA_EXERCICIO",
            },
        ),
    ]
