# Generated by Django 5.2.17 on 2026-09-05 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("respostas", models.JSONField()),
                ("nivel_atribuido", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "TB_SESSAO_TRIAGEM",
            },
        ),
        migrations.CreateModel(
            name="TriagemInicial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respostas", models.JSONField()),
                ("nivel_atribuido", models.CharField(max_length=50)),
                ("realizada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sessao_triagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="placement.sessaotriagem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triagens",
                        to="accounts.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "TB_TRIAGEM_INICIAL",
            },
        ),
    ]
