# Generated by Django 5.2.17 on 2026-09-19 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enunciado", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("texto", "Texto"), ("partitura", "Partitura")],
                        default="texto",
                        max_length=50,
                    ),
                ),
                ("dados_partitura", models.JSONField(blank=True, null=True)),
                ("ordem", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "TB_PERGUNTA_TRIAGEM",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="SessaoTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("respostas", models.JSONField()),
                ("nivel_atribuido", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "TB_SESSAO_TRIAGEM",
            },
        ),
        migrations.CreateModel(
            name="OpcaoTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("peso_perfil", models.IntegerField(default=1)),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcoes",
                        to="placement.perguntatriagem",
                    ),
                ),
            ],
            options={
                "db_table": "TB_OPCAO_TRIAGEM",
            },
        ),
        migrations.CreateModel(
            name="TriagemInicial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respostas", models.JSONField()),
                ("nivel_atribuido", models.CharField(max_length=50)),
                ("realizada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sessao_triagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="placement.sessaotriagem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triagens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "TB_TRIAGEM_INICIAL",
            },
        ),
    ]
