# Generated by Django 5.2.17 on 2026-09-05 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enunciado", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("texto", "Texto"), ("partitura", "Partitura")],
                        default="texto",
                        max_length=50,
                    ),
                ),
                ("dados_partitura", models.JSONField(blank=True, null=True)),
                ("ordem", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "TB_PERGUNTA_TRIAGEM",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="OpcaoTriagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("peso_perfil", models.IntegerField(default=1)),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcoes",
                        to="placement.perguntatriagem",
                    ),
                ),
            ],
            options={
                "db_table": "TB_OPCAO_TRIAGEM",
            },
        ),
    ]
